import type { Metadata } from "next";
import LayoutWrapper from "./Components/layoutwrapper";
import Footer from "./Components/Footer";
import "@/globals.css";

export const metadata: Metadata = {
  title: "MachKnow Soft",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans">
        <LayoutWrapper>
          <div className="max-w-[100%] mx-auto min-h-screen bg-[#0F172A]">
            {children}
            <Footer />
          </div>
        </LayoutWrapper>
      </body>
    </html>
  );
}
